CREATE TRIGGER AE_ATELIERS_TRG 
BEFORE INSERT ON AE_ATELIERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_ATELIER IS NULL THEN
      SELECT AE_ATELIERS_SEQ.NEXTVAL INTO :NEW.ID_ATELIER FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
