CREATE TRIGGER AE_AUDITEURS_TRG 
BEFORE INSERT ON AE_AUDITEURS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_AUDITEUR IS NULL THEN
      SELECT AE_AUDITEURS_SEQ.NEXTVAL INTO :NEW.ID_AUDITEUR FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
