CREATE OR REPLACE TRIGGER AE_EVENEMENT_TRG 
BEFORE INSERT OR DELETE OR UPDATE ON AE_INSCRIPTION_ARCHIVE
FOR EACH ROW
BEGIN
  IF INSERTING THEN 
    EVENEMENT := 'insertion'
  ELSE IF UPDATING THEN
    EVENEMENT := 'modification'
  ELSE IF DELETING THEN
    EVENEMENT := 'suppression'
  END IF;
END;
/
