CREATE TRIGGER AE_INSCRIPTION_ARCHIVE_TRG 
BEFORE INSERT ON AE_INSCRIPTION_ARCHIVE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.NO_INS_ARCH IS NULL THEN
      SELECT AE_INSCRIPTION_ARCHIVE_SEQ.NEXTVAL INTO :NEW.NO_INS_ARCH FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
