CREATE TRIGGER P_ATELIERS_TRG 
BEFORE INSERT ON P_ATELIERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_ATELIER IS NULL THEN
      SELECT P_ATELIERS_SEQ.NEXTVAL INTO :NEW.ID_ATELIER FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
