CREATE TRIGGER P_CATEGORIE_ATELIER_TRG 
BEFORE INSERT ON P_CATEGORIE_ATELIER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_CATEGORIE IS NULL THEN
      SELECT P_CATEGORIE_ATELIER_SEQ.NEXTVAL INTO :NEW.ID_CATEGORIE FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
