CREATE TRIGGER P_JURY_TRG 
BEFORE INSERT ON P_JURY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_JURY IS NULL THEN
      SELECT P_JURY_SEQ.NEXTVAL INTO :NEW.ID_JURY FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
