CREATE TRIGGER P_TYPE_ATELIER_TRG 
BEFORE INSERT ON P_TYPE_ATELIER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_TYPE IS NULL THEN
      SELECT P_TYPE_ATELIER_SEQ.NEXTVAL INTO :NEW.ID_TYPE FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
