package model.views;

import model.views.common.PAuditeurView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 30 17:36:53 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAuditeurViewImpl
  extends ViewObjectImpl
  implements PAuditeurView
{
  /**
   * This is the default constructor (do not remove).
   */
  public PAuditeurViewImpl()
  {
  }

  /**
   * Returns the bind variable value for loginBind.
   * @return bind variable value for loginBind
   */
  public String getloginBind()
  {
    return (String) getNamedWhereClauseParam("loginBind");
  }

  /**
   * Sets <code>value</code> for bind variable loginBind.
   * @param value value to bind as loginBind
   */
  public void setloginBind(String value)
  {
    setNamedWhereClauseParam("loginBind", value);
  }

  /**
   * Returns the bind variable value for mdpBind.
   * @return bind variable value for mdpBind
   */
  public String getmdpBind()
  {
    return (String) getNamedWhereClauseParam("mdpBind");
  }

  /**
   * Sets <code>value</code> for bind variable mdpBind.
   * @param value value to bind as mdpBind
   */
  public void setmdpBind(String value)
  {
    setNamedWhereClauseParam("mdpBind", value);
  }
  
  public int auditeurConnecte(String login, String mdp)
  {
    this.setloginBind(login);
    this.setmdpBind(mdp);
    this.executeQuery();
    int retour = 0;
    
    System.out.println(login+" - "+mdp);
    System.out.println(this.getRowCount());
    
    if (this.getRowCount() > 0)
    {
      System.out.println("passé");
      this.next();
      int admin = ((PAuditeurViewRowImpl)this.getCurrentRow()).getAdmin();
      System.out.println(admin);
      if(admin == 1)
      {
        retour = admin;
      }
      else
      {
        retour = 2;
      }
    }
    else
    {
      retour = 3;
    }
    return retour;
  }
}