package model.views.client;

import model.views.common.PAuditeurView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 07 17:01:10 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAuditeurViewClient
  extends ViewUsageImpl
  implements PAuditeurView
{
  /**
   * This is the default constructor (do not remove).
   */
  public PAuditeurViewClient()
  {
  }

  public int auditeurConnecte(String login, String mdp)
  {
    Object _ret =
      getApplicationModuleProxy().riInvokeExportedMethod(this,"auditeurConnecte",new String [] {"java.lang.String","java.lang.String"},new Object[] {login, mdp});
    return ((Integer)_ret).intValue();
  }
}
