package model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 07 17:01:07 EDT 2013
// ---------------------------------------------------------------------
public interface PAuditeurView
  extends ViewObject
{
  int auditeurConnecte(String login, String mdp);
}
